import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* suppressHydrationWarning: ColorZilla 등 브라우저 확장이 <body>에 속성(cz-shortcut-listen 등)을
          주입해 생기는 하이드레이션 경고를 억제한다. body 한 단계 속성만 해당되며, 내부 컴포넌트의
          실제 불일치는 그대로 감지된다. (Next.js 공식 권장 — 확장 프로그램 주입 케이스) */}
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
